apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: traffic-generator-policy
  namespace: demo
spec:
  endpointSelector:
    matchLabels:
      app: traffic-generator
  egress:
  # Allow DNS
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
  # Allow communication to backend
  - toEndpoints:
    - matchLabels:
        app: backend
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  # Allow communication to frontend
  - toEndpoints:
    - matchLabels:
        app: frontend
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP